version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  image: latest
  tools:
    python: "3.8"

conda:
  environment: environment.yml

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - all

formats: []
