name: kelp

channels:
    - astropy

dependencies:
    - python>=3.5
    - astropy
    - Cython
    - matplotlib
    - numpy
    - sphinx-astropy
    - pip:
       - scipy
       - tynt
       - batman-package