name: kelp
channels:
  - conda-forge
dependencies:
  - llvm
  - clang-11
  - pip:
    - pytest-astropy
    - git+https://github.com/exoplanet-dev/exoplanet.git
    - git+https://github.com/exoplanet-dev/pymc-ext.git
    - pymc>4,<5