[build-system]

requires = [
    "setuptools",
    "setuptools_scm",
    "wheel",
    "extension-helpers",
    "numpy",
    "pytest-astropy",
    "cython==0.29.14"
]

build-backend = 'setuptools.build_meta'
